// <auto-generated />
using System;
using Aspire.Sample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aspire.Sample.Data.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712202943_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aspire.Sample.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 7, 11),
                            Summary = "Seeded",
                            TemperatureC = 101
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 7, 10),
                            Summary = "Seeded",
                            TemperatureC = 102
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 7, 9),
                            Summary = "Seeded",
                            TemperatureC = 103
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
